# Configuration for actionlint
# https://github.com/rhysd/actionlint/blob/main/docs/config.md

self-hosted-runner:
  # Custom labels used by our self-hosted runners
  labels:
    - vm
    - debian-11
    - debian-12
    - xl
    - m
    - claude-code

# Ignore certain shellcheck rules from run: blocks in workflow files.
# These are overly pedantic for CI workflow scripts where the inputs are
# controlled by GitHub Actions expressions.
paths:
  .github/workflows/*.yml:
    ignore:
      - 'SC1090:'  # Can't follow non-constant source
      - 'SC2046:'  # Quote command substitution to prevent word splitting
      - 'SC2086:'  # Double quote to prevent globbing and word splitting
      - 'SC2143:'  # Use grep -q instead of comparing output with [ -n .. ]
