FROM ubuntu
RUN echo "test" > file
RUN mkdir directory
RUN echo "test" > directory/directoryfile
RUN echo "test" > anotherfile
RUN mkdir anotherdirectory
RUN echo "test" > anotherdirectory/anotherfile

RUN rm file
RUN rm -rf directory
